WebApplication1/Models/Films.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Films
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string FavChar { get; set; }
        public string Poster { get; set; }
        public string SSka { get; set; }
    }
}

WebApplication1/Models/FilmsList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class FilmsList
    {
        public static List<Films> DescrFilm()
        {
            List<Films> f= new List<Films>();
            f.Add(new Films()
            {
                Name = "Молчание ягнят",
                Description = "«Молчание ягнят» — американский триллер 1991 года режиссёра Джонатана Демми, снятый по мотивам одноимённого романа Томаса Харриса о Ганнибале Лектере.",
                FavChar = "Доктор Ганнибал Лектер",
                Poster = "http://st.kp.yandex.net/images/film_big/345.jpg",
                SSka = "https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D0%BB%D1%87%D0%B0%D0%BD%D0%B8%D0%B5_%D1%8F%D0%B3%D0%BD%D1%8F%D1%82_(%D1%84%D0%B8%D0%BB%D1%8C%D0%BC)"
            });
            f.Add(new Films()
            {
                Name = "Алиса в стране чудес",
                Description = "«Алиса в Стране чудес» — фэнтезийный приключенческий фильм 2010 года, снятый Тимом Бёртоном по сценарию Линды Вулвертон с участием Мии Васиковской, Джонни Деппа, Хелены Бонэм Картер, Энн Хэтэуэй, Криспина Гловера, Майкла Шина и Стивена Фрая.",
                FavChar = "Шляпник",
                Poster = "http://st.kp.yandex.net/images/film_iphone/iphone360_405609.jpg",
                SSka = "https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B8%D1%81%D0%B0_%D0%B2_%D0%A1%D1%82%D1%80%D0%B0%D0%BD%D0%B5_%D1%87%D1%83%D0%B4%D0%B5%D1%81_(%D1%84%D0%B8%D0%BB%D1%8C%D0%BC,_2010)"
            });
            f.Add(new Films()
            {
                Name = "Гордость и предубеждение",
                Description = "«Гордость и предубеждение» — фильм 2005 года режиссёра Джо Райта по мотивам одноимённого романа Джейн Остин 1813 года. Главную роль исполняет Кира Найтли.",
                FavChar = "Элизабет Беннет",
                Poster = "http://st.kp.yandex.net/images/film_big/81733.jpg",
                SSka = "https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%B4%D0%BE%D1%81%D1%82%D1%8C_%D0%B8_%D0%BF%D1%80%D0%B5%D0%B4%D1%83%D0%B1%D0%B5%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5_(%D1%84%D0%B8%D0%BB%D1%8C%D0%BC,_2005)"
            });
            return f;
        }
    }
}

WebApplication1/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Study()
        {
            return View();
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Films()
        {
            var f = FilmsList.DescrFilm();
            return View(f);
        }
    }
}

WebApplication1/Views/About/Index.cshtml
@{
    Layout = "../Shared/_Layout.cshtml";
}
<html>
<head>
    <title>Увлечения</title>
</head>
<body>
    <div style='text-align: center'>
        <h2><FONT COLOR="#0000CD">Мои увлечения</FONT></h2>
        </div>
        <div>
            <ul>
                <li>Увлекаюсь программированием</li>
                <li>Люблю гулять по городу в хорошую погоду</li>
                <li>Люблю кататься на велосипеде</li>
                <li>Мне нравится читать</li>
                <li>Хочу изучать немецкий язык</li>
            </ul>
            <IMG SRC="https://pp.vk.me/c627219/v627219373/2ff76/V151EgCLrrY.jpg" TITLE="Вот такое вот иногда можно встетить на прогулке">
        </div>
</body>
</html>

WebApplication1/Views/About/Study.cshtml
@{
    Layout = "../Shared/_Layout.cshtml";
}
<html>
<head>
    <title>Обучение</title>
</head>
<body>
    <div style='text-align: center'>
        <h2><FONT COLOR="#0000CD">Мое обучение</FONT></h2>
    </div>
    <div>
        <ul>
            <li>С первого по третий класс училась в школе №36 города Мурманска</li>
            <li>С четвертого по восьмой класс училась в гимназии №92 города Санкт-Петербурга</li>
            <li>С девятого по одиннадцатый класс училась в Презедентском физ-мат лицее №239</li>
            <li>В настоящий момент учусь на первом курсе университета ИТМО, факультет Информационных технологий и программирования, на направлении "Прикладная информатика в экономике"</li>
        </ul>
    </div>
    <a href="http://www.ifmo.ru/"><IMG SRC= "http://media.ifmo.ru/images/photos/big/p56.jpg" /></a>
    </body>
</html>

WebApplication1/Views/Home/Films.cshtml
@{
    Layout = "../Shared/_Layout.cshtml";
}

<html>
<head>
    <title>Любимые фильмы</title>
</head>
<body>
    <div style='text-align: center'>
        <h2><FONT COLOR="#0000CD">Мои любимые фильмы</FONT></h2>
    </div>
    <div>
        <ul>
            @foreach (var f in Model)
            {
                <li>
                    <B>Название: </B>@(f.Name)<BR> 
                    <B>Описание: </B>@(f.Description) <BR> 
                    <B>Любимый персонаж: </B>@(f.FavChar) <BR>
                    <a href="@(f.SSka)"><IMG SRC="@(f.Poster)" HEIGHT="500"></a>
                </li>
            }
        </ul>
    </div>
    </body>
</html>

WebApplication1/Views/Home/Index.cshtml
@{
    Layout = null;
}

<html>
<head>
    <title>Анна Ратникова</title>
    <style>
        body {
            background: #FFEFD5; /* Цвет фона */
        }
    </style>
</head>
<body>
    <div style='text-align: center'>
        <h1><B><FONT COLOR="#8B008B">Ратникова Анна</FONT></B></h1><hr>
        <p>
            <a href="https://vk.com/id23709373"><IMG SRC="https://pp.vk.me/c628719/v628719373/6438c/7lhj5MVIMeY.jpg" alt="Это я :)" TITLE="Это я :)" HEIGHT="500"></a>
        </p>
    </div>
        <h2><FONT COLOR="#0000CD">Что вы хотите знать обо мне?</FONT></h2>
        <p>
            <ul>
                <li>@Html.ActionLink("Мое обучение", "Study", "About")</li>
                <li>@Html.ActionLink("Увлечения", "Index", "About")</li>
                <li>@Html.ActionLink("Мои любимые фильмы", "Films", "Home")</li>
            </ul>
        </p>
</body>
</html>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            background: #FFEFD5; /* Цвет фона */
        }
    </style>
</head>
<body>
    @Html.ActionLink("Главная", "Index", "Home")
        <div>
            @RenderBody()
        </div>

</body>
</html>